### ISSUE TITLE
Tidy up magic values

### ISSUE THREAD

**Issue by dfollent** [xmos/lib_agc#110]
The EWMA alpha value for the weighted average of the correlation factor uses a 'magic number' rather than a defined constant.

https://github.com/xmos/lib_agc/blob/5671316b9d9b30d640f7bc650a2a95c2e2cc1a5d/lib_agc/src/agc.xc#L385

https://github.com/xmos/lib_agc/blob/5671316b9d9b30d640f7bc650a2a95c2e2cc1a5d/python/agc.py#L96

This should be defined as a hash define alongside the other EWMA alpha values used in the AGC block.

**Comment by mbanth** [comment]
I'm closing this issue because we do not expect to improve the applications that use lib_agc unless we receive a specific request from an external customer.
